# Generated by Django 6.0.4 on 2026-10-07 12:41

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_manager', models.BooleanField(default=False)),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='core.organization')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('declaration_close_weekday', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Poniedziałek'), (1, 'Wtorek'), (2, 'Środa'), (3, 'Czwartek'), (4, 'Piątek'), (5, 'Sobota'), (6, 'Niedziela')], help_text='Dzień tygodnia zamknięcia okna deklaracji. Puste = bez limitu.', null=True)),
                ('declaration_close_time', models.TimeField(blank=True, help_text='Godzina zamknięcia w wybranym dniu (np. 23:59).', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_settings', to='core.organization')),
            ],
            options={
                'verbose_name': 'Ustawienia grafiku',
                'verbose_name_plural': 'Ustawienia grafiku',
            },
        ),
        migrations.CreateModel(
            name='ShiftTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('is_active', models.BooleanField(default=True)),
                ('max_slots', models.PositiveSmallIntegerField(default=1, help_text='Maksymalna liczba zatwierdzonych osób na tę zmianę w jednym dniu.')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_templates', to='core.organization')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ShiftTemplateHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Poniedziałek'), (1, 'Wtorek'), (2, 'Środa'), (3, 'Czwartek'), (4, 'Piątek'), (5, 'Sobota'), (6, 'Niedziela')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hours', to='core.shifttemplate')),
            ],
            options={
                'ordering': ['weekday'],
            },
        ),
        migrations.CreateModel(
            name='TaskType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_types', to='core.organization')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WorkDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='proposed', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.CharField(blank=True, default='', max_length=255)),
                ('note', models.CharField(blank=True, default='', help_text='Opcjonalna notatka pracownika (np. wcześniejsze wyjście).', max_length=500)),
                ('rate_at_time', models.DecimalField(decimal_places=2, editable=False, max_digits=10, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_workdays', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workdays', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tasktype')),
                ('shift_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workdays', to='core.shifttemplate')),
            ],
        ),
        migrations.CreateModel(
            name='SwapRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted_by_target', models.BooleanField(default=False)),
                ('approved_by_manager', models.BooleanField(default=False)),
                ('is_rejected', models.BooleanField(default=False)),
                ('rejection_reason', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_swaps', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_swaps', to=settings.AUTH_USER_MODEL)),
                ('target_work_day', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incoming_swaps', to='core.workday')),
                ('work_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_swaps', to='core.workday')),
            ],
        ),
        migrations.CreateModel(
            name='RejectionReasonTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('sort_order', models.PositiveSmallIntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rejection_reasons', to='core.organization')),
            ],
            options={
                'verbose_name': 'Szablon powodu odrzucenia',
                'verbose_name_plural': 'Szablony powodów odrzucenia',
                'ordering': ['sort_order', 'text'],
                'constraints': [models.UniqueConstraint(fields=('organization', 'text'), name='unique_rejection_reason_per_org')],
            },
        ),
        migrations.AddConstraint(
            model_name='shifttemplate',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='unique_shift_template_name_per_org'),
        ),
        migrations.AddConstraint(
            model_name='shifttemplatehours',
            constraint=models.UniqueConstraint(fields=('template', 'weekday'), name='unique_hours_per_template_weekday'),
        ),
        migrations.AddConstraint(
            model_name='tasktype',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='unique_task_type_name_per_org'),
        ),
        migrations.AddConstraint(
            model_name='workday',
            constraint=models.UniqueConstraint(fields=('employee', 'date'), name='unique_workday_per_employee_date'),
        ),
    ]
