# Generated by Django 6.0.3 on 2026-07-13 20:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_approve_existing_workdays'),
    ]

    operations = [
        migrations.AddField(
            model_name='swaprequest',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='swaprequest',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='swaprequest',
            name='rejection_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
