# Generated by Django 6.0.4 on 2026-08-19 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_rebrand_organization_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='organization',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='core.organization'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paymentsession',
            name='session_id',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='schedulesettings',
            name='declaration_close_weekday',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Poniedziałek'), (1, 'Wtorek'), (2, 'Środa'), (3, 'Czwartek'), (4, 'Piątek'), (5, 'Sobota'), (6, 'Niedziela')], help_text='Dzień tygodnia zamknięcia okna deklaracji (0=poniedziałek … 6=niedziela). Puste = bez limitu.', null=True),
        ),
    ]
