# Generated by Django 6.0.4 on 2026-08-19 08:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_employeeprofile_organization_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='owners',
            field=models.ManyToManyField(related_name='owned_organizations', to=settings.AUTH_USER_MODEL),
        ),
    ]
