# Generated by Django 6.0.4 on 2026-08-19 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_organization_owners'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
