# Generated by Django 6.0.4 on 2026-09-11 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_employeeprofile_is_active_organization_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.organization'),
        ),
    ]
